# Newton's Method for Optimization

## Example 1: Quadratic Function Minimization

In [1]:
%matplotlib widget

In [2]:
import matplotlib.pyplot as plt
import matplotlib
import numpy as np
from matplotlib import cm
from mpl_toolkits.mplot3d import Axes3D

$f: (x_1,x_2) \mapsto (x_1-2)^2 + 2(x_2+1)^2+1$

$\nabla f(x_1, x_2) = \begin{pmatrix} 2(x_1-2) \\ 4(x_2+1) \end{pmatrix} = \begin{pmatrix} 2x_1-4 \\ 4x_2+4 \end{pmatrix}$

$H_f(x_1, x_2) = \begin{pmatrix} 2 & 0 \\ 0 & 4 \end{pmatrix}$

In [3]:
def f(x_1,x_2):
    return (x_1-2)**2 + 2*(x_2+1)**2 +1
def grad_f(x_1,x_2):
    return np.array([(2*x_1-4), (4*x_2+4)])
def hessian_f(x_1,x_2):
    return np.array([(2,0), (0,4)])

In [4]:
x_1 = np.arange(-4,4,0.1)
x_2 = np.arange(-4,4,0.1)
X_1,X_2 = np.meshgrid(x_1,x_2)

In [5]:
X_3 = f(X_1, X_2)
fig=plt.figure()
ax = Axes3D(fig)
ax.plot_surface(X_1,X_2,X_3,cmap=cm.viridis)
ax.set_xlabel("x1")
ax.set_ylabel("x2")
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [6]:
plt.close()
fig,ax = plt.subplots()
ax.set_aspect(aspect=1)
CS = ax.contour(X_1,X_2,X_3, levels=[2,4.28,6,8,10,15,20,25,30,35,40])
ax.clabel(CS, inline=1, fontsize=10)
ax.plot(2,-1,"o")
ax.set_xlabel("x1")
ax.set_ylabel("x2");

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [7]:
ax.plot([-4,2,2], [-1,-1,-4], "--");

### Step 1:
starting point: 
$x^{(0)} = (-2,2)$

In [8]:
f(-2,2)

35

In [9]:
plt.close()
fig,ax = plt.subplots()
ax.set_aspect(aspect=1)
CS = ax.contour(X_1,X_2,X_3, levels=[2,4.28,6,8,10,15,20,25,30,35,40])
ax.clabel(CS, inline=1, fontsize=10)
ax.plot(2,-1,"o")
ax.plot(-2,2,"o");
ax.set_xlabel("x1")
ax.set_ylabel("x2");

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [10]:
-grad_f(-2,2)

array([  8, -12])

In [11]:
hessian_f(-2,2)

array([[2, 0],
       [0, 4]])

In [12]:
v = np.linalg.solve(hessian_f(-2,2), -grad_f(-2,2));v

array([ 4., -3.])

In [13]:
plt.close()
fig,ax = plt.subplots()
ax.set_aspect(aspect=1)
CS = ax.contour(X_1,X_2,X_3, levels=[2,4.28,6,8,10,15,20,25,30,35,40])
ax.clabel(CS, inline=1, fontsize=10)
ax.plot(2,-1,"o")
ax.plot([-2,2],[2,-1],'o--',markevery=[0])
ax.set_xlabel("x1")
ax.set_ylabel("x2");

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

$x^{(1)} = \begin{pmatrix} -2\\ 2 \end{pmatrix} + \begin{pmatrix} 4 \\ -3 \end{pmatrix} = \begin{pmatrix} 2 \\ -1 \end{pmatrix}$

## Example 2: A higher order function


$f: (x_1,x_2) \mapsto (x_1-2)^4 + 2(x_1+1)^2 \cdot (x_2+1)^2 + (x_2-1)^4 + 1$

$\nabla f(x_1, x_2) = \begin{pmatrix} 4(x_1-2)^3 +4(x_1+1)(x_2+1)^2 \\ 4(x_1+1)^2(x_2+1) + 4(x_2-1)^3 \end{pmatrix}$

$H_f(x_1, x_2) = \begin{pmatrix} 12(x_1-2)^2 + 4(x_2+1)^2 & 8(x_1+1)(x_2+1) \\ 8(x_1+1)(x_2+1) & 12(x_2-1)^2 \end{pmatrix}$

In [14]:
def f(x_1,x_2):
    return (x_1-2)**4 + 2*(x_2+1)**2*(x_1+1)**2 + (x_2-1)**4 +1

def grad_f(x_1,x_2):
    return  np.array([(4*(x_1-2)**3 + 4*(x_1+1)*(x_2+1)**2), 4*(x_1+1)**2*(x_2+1) + 4*(x_2-1)**3])

def hessian_f(x_1,x_2):
    return np.array([ ( 12*(x_1-2)**2 + 4*(x_2+1)**2 , 8*(x_1+1)*(x_2+1) ) , ( 8*(x_1+1)*(x_2+1) , 12*(x_2-1)**2)])

In [15]:
x_1 = np.arange(-3,3,0.1)
x_2 = np.arange(-3,3,0.1)
X_1,X_2 = np.meshgrid(x_1,x_2)

In [16]:
X_3 = f(X_1, X_2)
fig=plt.figure()
ax = Axes3D(fig)
ax.plot_surface(X_1,X_2,X_3,cmap=cm.viridis)
ax.set_xlabel("x1")
ax.set_ylabel("x2")
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [17]:
plt.close()
fig,ax = plt.subplots()
ax.set_aspect(aspect=1)
CS = ax.contour(X_1,X_2,X_3, levels=[2,4,6,8,10,15,20,25,30,35,40,50,60,80,100,120,150,200,250,300,400,500])
ax.clabel(CS, inline=1, fontsize=10)
ax.set_xlabel("x1")
ax.set_ylabel("x2");

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

### Algorithm:
starting point: 
$x^{(0)} = (1,0)$

In [18]:
plt.close()
fig,ax = plt.subplots()
ax.set_aspect(aspect=1)
CS = ax.contour(X_1,X_2,X_3, levels=[2,4,6,8,10,15,20,25,30,35,40,50,60,80,100,120,150,200,250,300,400,500])
ax.clabel(CS, inline=1, fontsize=10)
ax.plot(1,0,"o",color='orange');
ax.set_xlabel("x1")
ax.set_ylabel("x2");

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [19]:
f(1,0)

11

In [20]:
grad_f(1,0)

array([ 4, 12])

In [21]:
hessian_f(1,0)

array([[16, 16],
       [16, 12]])

In [22]:
p = [np.array([1,0])]
k = 0
#while np.any(grad_f(*p[k]) != 0):
while (np.linalg.norm(grad_f(*p[k])) > 0.0000001) and k < 100:
    v = np.linalg.solve(hessian_f(*p[k]), -grad_f(*p[k]));
    p.append(p[k]+v)
    k += 1
    print(f"new point: {p[k]}")

new point: [-1.25  2.  ]
new point: [-0.34898279  2.05467527]
new point: [0.11581839 0.76117066]
new point: [-0.58045621  4.01879491]
new point: [-0.33360746  2.94219456]
new point: [-0.11056218  2.03653772]
new point: [0.41356681 0.0673902 ]
new point: [ 1.16567145 -1.30895437]
new point: [ 1.9018609  -0.38710676]
new point: [ 1.6519723  -0.66486872]
new point: [-6.06163838  1.25552585]
new point: [-3.54764689 -0.79121417]
new point: [-1.69048289 -0.12967004]
new point: [-0.45116347  0.52757071]
new point: [ 0.43593596 -2.22369533]
new point: [ 1.11562587 -0.99158327]
new point: [ 1.40032957 -0.33174021]
new point: [ 1.29973991 -0.55082268]
new point: [ 0.82958134 -0.22850989]
new point: [ 1.15847504 -0.59443854]
new point: [ 1.02289999 -0.27958652]
new point: [ 1.25817267 -0.59282567]
new point: [ 0.93693765 -0.25706643]
new point: [ 1.21869804 -0.59705437]
new point: [ 0.98285017 -0.26881911]
new point: [ 1.24204636 -0.59672366]
new point: [ 0.95932102 -0.26267845]
new point: [ 1.23

**Both algorithms are not guaranteed to yield a useable result - they can clearly fail miserably!**

In [23]:
f(1.2, -0.6)

9.512000000000002

In [24]:
grad_f(1.2,-0.6)

array([-0.64, -8.64])